apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: safety-amp
  labels:
    app: safety-amp
    component: observability
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf
    [INPUT]
        Name   tail
        Path   /app/output/changes/*.json
        Parser json
        Tag    safetyamp.changes
    [INPUT]
        Name   tail
        Path   /app/output/errors/error_log.json
        Parser json
        Tag    safetyamp.errors
    [OUTPUT]
        Name        azure
        Match       safetyamp.*
        Customer_ID ${WORKSPACE_ID}
        Shared_Key  ${WORKSPACE_KEY}
        Log_Type    SafetyAmpCustom
  parsers.conf: |
    [PARSER]
      Name        json
      Format      json
      Time_Key    timestamp
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
---
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-metrics-scrape
  namespace: safety-amp
spec:
  podSelector:
    matchLabels:
      app: safety-amp
      component: agent
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: kube-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9090
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: safety-amp-servicemonitor
  namespace: safety-amp
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: safety-amp
      component: agent
  namespaceSelector:
    matchNames:
      - safety-amp
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: safetyamp-alerts
  namespace: safety-amp
  labels:
    app: safety-amp
    role: alert-rules
spec:
  groups:
  - name: safetyamp.rules
    rules:
    - alert: SafetyAmpSyncFailure
      expr: increase(safetyamp_sync_operations_total{status="error"}[5m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "SafetyAmp sync operation failed"
        description: "One or more sync operations failed in the last 5 minutes."
    - alert: SafetyAmpCacheStale
      expr: (time() - max by (cache) (safetyamp_cache_last_updated_timestamp_seconds)) > (max by (cache) (safetyamp_cache_ttl_seconds) * 1.25)
      for: 15m
      labels:
        severity: warning
        service: safety-amp
        team: integrations
      annotations:
        summary: "SafetyAmp cache is stale"
        description: "Cache {{ $labels.cache }} exceeded TTL by >25%."
        runbook_url: "file://k8s/monitoring/RUNBOOK.md#high-log-ingestion-cost"
    - alert: SafetyAmpErrorSurge
      expr: sum(increase(safetyamp_errors_total[15m])) > 20
      for: 5m
      labels:
        severity: critical
        service: safety-amp
        team: integrations
      annotations:
        summary: "Error surge detected"
        description: "More than 20 errors recorded in the last 15 minutes. Investigate recent changes and logs."
        runbook_url: "file://k8s/monitoring/RUNBOOK.md#alert-noise"
    - alert: SafetyAmpMissingSync
      expr: time() - max(safetyamp_last_sync_timestamp_seconds) > 5400
      for: 10m
      labels:
        severity: warning
        service: safety-amp
        team: integrations
      annotations:
        summary: "Missing sync activity"
        description: "No completed sync detected for >90 minutes. Verify worker health and /health endpoint."
        runbook_url: "file://k8s/monitoring/RUNBOOK.md#dashboards-blank-metrics"
    - alert: SafetyAmpLongRunningSyncP95
      expr: histogram_quantile(0.95, sum by (le, operation) (rate(safetyamp_sync_duration_seconds_bucket[15m]))) > 600
      for: 10m
      labels:
        severity: warning
        service: safety-amp
        team: integrations
      annotations:
        summary: "Long-running syncs (P95)"
        description: "P95 of sync duration exceeds 10 minutes for at least one operation. Check source/destination APIs."
        runbook_url: "file://k8s/monitoring/RUNBOOK.md#dashboards-blank-logs"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: container-azm-ms-agentconfig
  namespace: kube-system
  labels:
    component: container-insights
data:
  schema-version: |
    v1
  config-version: |
    ver1
  log-data-collection-settings: |-
    [log_collection_settings]
       [log_collection_settings.stdout]
          enabled = true
          exclude_namespaces = ["kube-system"]
       [log_collection_settings.stderr]
          enabled = true
          exclude_namespaces = ["kube-system"]
       [log_collection_settings.enrich_container_logs]
          enabled = true