apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: safety-amp-servicemonitor
  namespace: safety-amp
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: safety-amp
      component: agent
  namespaceSelector:
    matchNames:
      - safety-amp
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
