apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: safety-amp
  labels:
    app: safety-amp
    component: observability
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf
    [INPUT]
        Name   tail
        Path   /app/output/changes/*.json
        Parser json
        Tag    safetyamp.changes
    [INPUT]
        Name   tail
        Path   /app/output/errors/error_log.json
        Parser json
        Tag    safetyamp.errors
    [OUTPUT]
        Name        azure
        Match       safetyamp.*
        Customer_ID ${WORKSPACE_ID}
        Shared_Key  ${WORKSPACE_KEY}
        Log_Type    SafetyAmpCustom
  parsers.conf: |
    [PARSER]
      Name        json
      Format      json
      Time_Key    timestamp
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
