apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-metrics-scrape
  namespace: safety-amp
spec:
  podSelector:
    matchLabels:
      app: safety-amp
      component: agent
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: kube-system  # Managed addons/agents
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring  # kube-prometheus-stack namespace
      ports:
        - protocol: TCP
          port: 9090
