apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safety-amp.fullname" . }}-config
  namespace: {{ .Values.namespace | default "safety-amp" }}
  labels:
    {{- include "safety-amp.labels" . | nindent 4 }}
data:
  {{- include "safety-amp.configData" . | nindent 2 }}