apiVersion: v1
kind: Service
metadata:
  name: {{ include "safety-amp.fullname" . }}-service
  namespace: {{ .Values.namespace | default "safety-amp" }}
  labels:
    {{- include "safety-amp.labels" . | nindent 4 }}
    component: agent
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "safety-amp.selectorLabels" . | nindent 4 }}
    component: agent