apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: safety-amp-integration-hpa
  namespace: safety-amp
  labels:
    app: safety-amp
    component: agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: safety-amp-agent
  minReplicas: 1
  maxReplicas: 3
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics for sync operations (if metrics server supports)
  - type: Pods
    pods:
      metric:
        name: safetyamp_current_sync_operations
      target:
        type: AverageValue
        averageValue: "2"  # Scale up if more than 2 operations per pod
  
  # Scaling behavior configuration
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Percent
        value: 50  # Scale down max 50% of replicas at once
        periodSeconds: 60
      - type: Pods
        value: 1   # Scale down max 1 pod at once
        periodSeconds: 60
      selectPolicy: Min  # Use the most conservative policy
    scaleUp:
      stabilizationWindowSeconds: 60   # 1 minute
      policies:
      - type: Percent
        value: 100  # Scale up max 100% (double) at once
        periodSeconds: 60
      - type: Pods
        value: 2    # Scale up max 2 pods at once
        periodSeconds: 60
      selectPolicy: Max  # Use the most aggressive policy