apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-service-account
  namespace: n8n
  labels:
    app: n8n
  annotations:
    azure.workload.identity/client-id: "your-n8n-client-id"
    azure.workload.identity/tenant-id: "your-azure-tenant-id"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: safety-amp-service-account
  namespace: safety-amp
  labels:
    app: safety-amp
  annotations:
    azure.workload.identity/client-id: "your-safety-amp-client-id"
    azure.workload.identity/tenant-id: "your-azure-tenant-id"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: samsara-service-account
  namespace: samsara
  labels:
    app: samsara
  annotations:
    azure.workload.identity/client-id: "your-samsara-client-id"
    azure.workload.identity/tenant-id: "your-azure-tenant-id"
---
# RBAC for n8n
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: n8n
  name: n8n-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: n8n-role-binding
  namespace: n8n
subjects:
- kind: ServiceAccount
  name: n8n-service-account
  namespace: n8n
roleRef:
  kind: Role
  name: n8n-role
  apiGroup: rbac.authorization.k8s.io
---
# RBAC for SafetyAmp
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: safety-amp
  name: safety-amp-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: safety-amp-role-binding
  namespace: safety-amp
subjects:
- kind: ServiceAccount
  name: safety-amp-service-account
  namespace: safety-amp
roleRef:
  kind: Role
  name: safety-amp-role
  apiGroup: rbac.authorization.k8s.io
---
# RBAC for Samsara
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: samsara
  name: samsara-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: samsara-role-binding
  namespace: samsara
subjects:
- kind: ServiceAccount
  name: samsara-service-account
  namespace: samsara
roleRef:
  kind: Role
  name: samsara-role
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRole for monitoring and metrics access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader
subjects:
- kind: ServiceAccount
  name: n8n-service-account
  namespace: n8n
- kind: ServiceAccount
  name: safety-amp-service-account
  namespace: safety-amp
- kind: ServiceAccount
  name: samsara-service-account
  namespace: samsara